### ISSUE TITLE
你好 问一下在每个省份上显示数据 能不能实现

### ISSUE THREAD

**Issue by DingBaoYi** [huweijian5/RegionDetector#1]
最近需求 和这个相同 现在支持 在每个省份上面显示数据吗

**Comment by hijunmeng** [comment]
以什么样的方式显示数据，这个可能每个项目都有自己的特色，不通用，实现的意义不大 或者你可以发个设计图来看看 如果ui还是比较通用的 我考虑加上去

**Comment by DingBaoYi** [comment]
![1497407002 1](https://user-images.githubusercontent.com/24238249/27112736-7388cc9e-50eb-11e7-86af-6bf453dc9bbe.png)

**Comment by DingBaoYi** [comment]
你好是这样的ui 请问一下能实现嘛  非常感谢

**Comment by hijunmeng** [comment]
抱歉 仔细思考了下 发现这个目前还没法实现
